# Generated by Django 6.0.2 on 2026-02-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('plateform', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Plateform',
                'verbose_name_plural': 'Plateforms',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('img', models.URLField()),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('main_actors', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('type', models.CharField(choices=[('Film', 'Film'), ('Serie', 'Serie')], default='Film', max_length=10)),
                ('popularity', models.FloatField(default=0.0)),
                ('genres', models.ManyToManyField(blank=True, to='api.genres')),
                ('plateforms', models.ManyToManyField(blank=True, to='api.plateform')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'unique_together': {('title', 'release_year', 'director')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Friendship',
                'verbose_name_plural': 'Friendships',
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('seen', 'Déjà vu')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='api.films')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swipe',
                'verbose_name_plural': 'Swipes',
                'unique_together': {('user', 'film')},
            },
        ),
    ]
