# Generated by Django 6.0.2 on 2026-02-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Casting',
                'verbose_name_plural': 'Castings',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='films',
            unique_together={('tmdb_id', 'type')},
        ),
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.director'),
        ),
        migrations.RemoveField(
            model_name='films',
            name='main_actors',
        ),
        migrations.AddField(
            model_name='films',
            name='main_actors',
            field=models.ManyToManyField(blank=True, to='api.casting'),
        ),
    ]
