# Generated by Django 6.0.2 on 2026-02-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateform', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Plateform',
                'verbose_name_plural': 'Plateforms',
            },
        ),
        migrations.AddField(
            model_name='films',
            name='plateform',
            field=models.ManyToManyField(blank=True, to='api.plateform'),
        ),
    ]
