# Generated by Django 6.0.2 on 2026-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plateform_films_plateform'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='type',
            field=models.CharField(choices=[('Film', 'Film'), ('Serie', 'Serie')], default='Film', max_length=10),
        ),
    ]
