# Generated by Django 6.0.2 on 2026-02-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_casting_director_alter_films_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.director'),
        ),
    ]
