# Generated by Django 6.0.2 on 2026-03-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_films_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='type',
            field=models.CharField(choices=[('Film', 'Film'), ('Série', 'Série')], default='Film', max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('avatar-camera.svg', 'Caméra'), ('avatar-clapperboard.svg', 'Clap'), ('avatar-popcorn.svg', 'Popcorn'), ('avatar-reel.svg', 'Bobine'), ('avatar-ticket.svg', 'Ticket')], default='avatar-popcorn.svg', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
