# Generated by Django 6.0.2 on 2026-02-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendship_swipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='films',
            old_name='plateform',
            new_name='plateforms',
        ),
        migrations.AlterUniqueTogether(
            name='films',
            unique_together={('title', 'release_year', 'director')},
        ),
    ]
