# Generated by Django 6.0.2 on 2026-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_plateform_films_plateforms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
    ]
