# Generated by Django 6.0.2 on 2026-03-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_swipe_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'ordering': ['-popularity', '-release_year', 'title'], 'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AddField(
            model_name='films',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
