# Generated by Django 6.0.2 on 2026-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_films_options_films_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
