# Generated by Django 6.0.2 on 2026-03-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_email_notifications_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateform',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
