# Generated by Django 6.0.2 on 2026-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plateform_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='plateform',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
