# Generated by Django 6.0.2 on 2026-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_plateform_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='now_playing',
            field=models.BooleanField(default=False),
        ),
    ]
