# Generated by Django 6.0.2 on 2026-04-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_films_now_playing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_seen_with_friends',
            field=models.BooleanField(default=True),
        ),
    ]
