# Generated by Django 6.0.2 on 2026-05-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_share_seen_with_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
